#!/bin/bash
# Sets up the system without any user interaction.
# All the variables that is needed will be sourced from /info
# shellcheck disable=SC2154

user_setup() {
    prompt "Setting up the user $uName" work
    out useradd -m -G wheel "$uName"
    sed -i "/%wheel ALL=(ALL) ALL/s/^#//g" /etc/sudoers
    out echo "$uName:$userPass" | chpasswd
    work_done

    prompt "Setting up the root password" work
    out echo "root:$rootPW" | chpasswd
    work_done
}

system_setup() {
    local timeZ
    prompt "Setting up the system" work
    out systemctl enable NetworkManager
    work_done

    prompt "Setting up the timezone: $timeZ" work
    timeZ="$(curl -s "http://worldtimeapi.org/api/ip.txt" | grep timezone | awk '{print $2}')"
    log_variable "timeZ" "$timeZ"
    out ln -sf /usr/share/zoneinfo/"$timeZ" /etc/localtime
    out timedatectl set-timezone "$timeZ"
    # Enable Network Time Protocol (NTP) synchronization
    out timedatectl set-ntp true
    # Write the current software clock time to the hardware clock
    out hwclock --systohc
    work_done

    # TODO double locale problem
    prompt "Setting up the locale: $locale" work
    sed -i "/$locale/s/^#//g" /etc/locale.gen
    out localectl set-locale LANG="$locale"
    out locale-gen
    work_done

    prompt "Setting up the hostname: $hostname" work
    echo "$hostname" >/etc/hostname
    printf "127.0.0.1\tlocalhost\n::1\tlocalhost\n127.0.1.1	%s.localdomain	%s" "$hostname" "$hostname" >/etc/hosts
    work_done
}

trim_setup() {
    prompt "Enabling auto-trimming of SSDs" work
    out systemctl enable fstrim.timer
    work_done
}

hibernation_setup() {
    prompt "Modifying kernel parameters to allow for hibernation" work
    swapUUID=$(blkid -s UUID -o value "$swap")
    log_variable "swapUUID" "$swapUUID"
    # Modify kernel parameters and initramfs hooks
    sed -i "/GRUB_CMDLINE_LINUX=/c\GRUB_CMDLINE_LINUX=\"resume=UUID=$swapUUID\"" /etc/default/grub &&
        sed -i 's/\<keyboard\>/& resume/' /etc/mkinitcpio.conf # Add the resume hook after the keyboard hook
    work_done

    prompt "Regenerating the initramfs" work
    out mkinitcpio -p linux
    work_done
}

# https://wiki.archlinux.org/index.php/Makepkg#Parallel_compilation
makepkg_parallel() {
    prompt "Enabling parallel compilation and compression for makepkg" work
    out sed -i '/MAKEFLAGS=/c\MAKEFLAGS="-j$(nproc)"' /etc/makepkg.conf
    out sed -i '/COMPRESSXZ/c\COMPRESSXZ=(xz -c -z - --threads=0)' /etc/makepkg.conf
    work_done

    prompt "Enabling optimized compilation for makepkg" work
    out sed -i '/CFLAGS="-m/c\CFLAGS="-march=native -O2 -pipe -fno-plt"' /etc/makepkg.conf
    work_done
}

grub_setup() {
    local mountPoint
    [[ -n $uefi ]] && mountPoint="/efi/" || mountPoint="/boot/"
    out mkdir "$mountPoint"
    out mount "$bl" "$mountPoint"
    if [[ -n $uefi ]]; then
        prompt "Downloading additional dependencies for GRUB with UEFI" work
        out pacman -S --noconfirm --needed efibootmgr
        work_done

        prompt "Installing GRUB for UEFI" work
        # https://wiki.archlinux.org/index.php/GRUB#Installation_2
        # This currently installs it to $mountPoint/EFI/BOOT/BOOTX64.EFI (the default/fallback boot path) which might remove the Windows EFI executable there
        out grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory="$mountPoint" --removable
        work_done
    else
        # This hasn't been tested
        prompt "Installing GRUB for BIOS" work
        out grub-install --target=i386-pc "$fs"
        work_done
    fi

    prompt "Generating GRUB config" work
    out grub-mkconfig -o /boot/grub/grub.cfg
    work_done

    out umount "$bl"
}
# Sets up yay
yay_setup() {
    prompt "Installing yay" work
    userpath=/home/"$uName"/
    cd "$userpath" || exit
    out su -c "git clone https://aur.archlinux.org/yay.git" "$uName"
    cd yay || exit
    su -c "makepkg -s" "$uName"
    out pacman -U --needed --noconfirm -- *.xz
    cd ..
    rm -rf yay/
    cd /
    work_done
}

main() {
    # /info is written by the install script
    # shellcheck disable=SC1091
    source /info
    source /sharedfuncs
    # Shred file since it contains sensative info
    out shred -n25 --remove /info

    user_setup
    system_setup
    # This modifies the grub config, so we'll run this before configuring grub
    [[ -n $enableHibernation ]] && hibernation_setup
    grub_setup
    # Doing this before installaing yay might make the installation faster
    [[ -n $makepkgParallel ]] && makepkg_parallel
    yay_setup

    [[ -n $enableSSDTRIM ]] && trim_setup

    # Move files to $HOME
    if [[ -n $logging ]]; then
        mv "$logFile" /home/"$uName"/
    else
        mv "$errorfile" /home/"$uName"/
    fi
    [[ -n $debug ]] && mv "$variableLog" /home/"$uName"/

    prompt "Log files have been dropped in $HOME" green
}

main "$@"
