#!/bin/bash
# Shared functions between install and setup scripts

# prompt
# 1: message
# 2: color (green, yellow, blue, red)
prompt() {
    message="$1\033[0m\n"
    case $2 in
    green) message="\033[1;32m$message" ;;
    yellow) message="\033[1;33m$message" ;;
    red) message="\033[1;31m$message" ;;
    blue) message="\033[1;34m$message" ;;
    esac
    printf "$message"
}
