#!/bin/bash
branch="master"
[ -n "$dev" ] && branch="develop"
echo "Downloading from the $branch branch"

curl -O https://raw.githubusercontent.com/alx99/arch-ai/"$branch"/sharedfuncs
curl -O https://raw.githubusercontent.com/alx99/arch-ai/"$branch"/common_pkgs
curl -O https://raw.githubusercontent.com/alx99/arch-ai/"$branch"/setup
curl -O https://raw.githubusercontent.com/alx99/arch-ai/"$branch"/install

chmod +x install
if [ $EUID -ne 0 ]; then sudo ./install else ./install; fi
